#!/usr/bin/env python3
"""Convert the CEVA logo SVG into OpenSCAD 2D modules.

Input : logo/ceva_logo_2023.svg  (Wikimedia Commons, "Logo of CEVA Logistics
        (2023).svg", public domain as simple text/shapes; CEVA trademark)
Output: logo/ceva_logo.scad with
          ceva_word_2d()       navy "cev" letters
          ceva_accent_2d()     red "A"
          ceva_strapline_2d()  "LOGISTICS" (too fine to print at box size)
        all centred on the wordmark, Y up, in SVG px units; scale with
        CEVA_WORD_W / CEVA_WORD_H.

Usage: python3 tools/logo_to_scad.py   (needs svgelements, shapely, numpy)
"""
import os
import numpy as np
from shapely.geometry import Polygon, MultiPolygon, box
from shapely.ops import unary_union
from svgelements import SVG, Path

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'logo', 'ceva_logo_2023.svg')
OUT = os.path.join(HERE, '..', 'logo', 'ceva_logo.scad')
RED = '#ff0000'
STEP = 0.3       # px between samples along curves (~0.02 mm at box size)
SIMPLIFY = 0.08  # px


def path_geometry(el):
    g = None
    for sp in el.as_subpaths():
        sp = Path(sp)
        n = max(8, int(sp.length(error=1e-3) / STEP))
        pts = [(p.x, p.y) for p in (sp.point(t) for t in np.linspace(0, 1, n))]
        pg = Polygon(pts).buffer(0)
        if pg.area > 1e-3:
            g = pg if g is None else g.symmetric_difference(pg)   # even-odd holes
    return g


def polys(g):
    return list(g.geoms) if isinstance(g, MultiPolygon) else [g]


def scad_module(name, g, cx, cy):
    out = [f'module {name}() {{', '    union() {']
    for pg in polys(g):
        pg = pg.simplify(SIMPLIFY, preserve_topology=True)
        def pts(ring):
            c = list(ring.coords)[:-1]
            return '[' + ','.join(f'[{x - cx:.3f},{cy - y:.3f}]' for x, y in c) + ']'
        if pg.interiors:
            out.append('        difference() {')
            out.append(f'            polygon({pts(pg.exterior)});')
            for h in pg.interiors:
                out.append(f'            polygon({pts(h)});')
            out.append('        }')
        else:
            out.append(f'        polygon({pts(pg.exterior)});')
    out += ['    }', '}']
    return '\n'.join(out)


def main():
    svg = SVG.parse(SRC, reify=True)
    navy, red = [], []
    for el in svg.elements():
        if isinstance(el, Path) and el.fill is not None and el.fill.value is not None:
            g = path_geometry(el)
            if g is not None:
                (red if el.fill.hex.lower() == RED else navy).append(g)
    navy = unary_union(navy)
    red = unary_union(red)
    split = 87.0                                  # px, between wordmark and strapline
    word = navy.intersection(box(-10, -10, 1000, split))
    strap = navy.intersection(box(-10, split, 1000, 1000))
    wx0, wy0, wx1, wy1 = unary_union([word, red]).bounds
    cx, cy = (wx0 + wx1) / 2, (wy0 + wy1) / 2
    with open(OUT, 'w') as f:
        f.write('// Generated by tools/logo_to_scad.py from logo/ceva_logo_2023.svg - do not edit.\n')
        f.write('// CEVA Logistics wordmark; units = SVG px, origin = wordmark centre, Y up.\n')
        f.write(f'CEVA_WORD_W = {wx1 - wx0:.3f};\nCEVA_WORD_H = {wy1 - wy0:.3f};\n\n')
        f.write(scad_module('ceva_word_2d', word, cx, cy) + '\n\n')
        f.write(scad_module('ceva_accent_2d', red, cx, cy) + '\n\n')
        f.write(scad_module('ceva_strapline_2d', strap, cx, cy) + '\n')
    print(f'{OUT}: wordmark {wx1 - wx0:.1f} x {wy1 - wy0:.1f} px')


if __name__ == '__main__':
    main()
